# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - master
    - develop

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: DeleteFiles@1
      displayName: 'delete JUnit files'
      inputs:
          SourceFolder: junit
          Contents: 'TEST*.xml'

    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'npm install'
      inputs:
          command: install

    - task: Npm@1
      displayName: 'unit tests'
      inputs:
          command: custom
          customCommand: run test

    - task: PublishTestResults@2
      displayName: 'Publish unit test results'
      condition: succeededOrFailed()
      inputs:
          searchFolder: $(System.DefaultWorkingDirectory)/junit
          testRunTitle: Angular
          testResultsFormat: JUnit
          testResultsFiles: '**/TESTS*.xml'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage unit test results'
      condition: succeededOrFailed()
      inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'coverage/cobertura-coverage.xml'
          reportDirectory: coverage
          failIfCoverageEmpty: true

    # - script: |
    #       bash <(curl https://codecov.io/bash) -t <YourCodeCovKeyHere> -f coverage/cobertura-coverage.xml -F adder -F subtractor
    #   displayName: 'codecov'

    - task: Npm@1
      displayName: 'build package'
      inputs:
          command: custom
          customCommand: run build

    - task: PublishPipelineArtifact@0
      inputs:
          artifactName: 'angular'
          targetPath: 'dist'
